server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///C:/Projects/shopverse/shopverse-config
          clone-on-start: true
